### PR TITLE
added empty_edges keyword

### PR DESCRIPTION
**Pull request by nwlandry**
A user reached out and asked if we could allow empty edges. I added the `empty_edges` as an optional keyword to opt-in to this behavior.

### CODE REVIEW

**Comment by leotrs** [comment]
I believe at some point we allowed for empty edges and then decided not to support them. Is this the case? If so, does anyone remember why we decided not tu support them?

**Comment by maximelucas** [comment]
> Is this the case?
 I don't remember honestly. Do we know what the use-case would be?

**Comment by leotrs** [comment]
@nwlandry :)

**Comment by nwlandry** [comment]
I originally wanted to include them to represent physical rooms without people in them. One of my colleagues wanted to represent groups that xould have 0 members. Lastly, there are several existing inconsistencies in XagI mentioned in #403.

**Comment by leotrs** [comment]
Okay yeah that sounds like a legit use case. We could try to implement this and the wait and see what breaks.

One caveat is that we'd need a whole battery of tests (several dozens) to test for integration of different corners of the library with empty edges.

**Comment by nwlandry** [comment]
This PR is stale and so I'm closing this. I will work on re-opening this in the future.

**Pull request closed without merging**
