### PR TITLE
Initial sphinx-gallery 

### PR DESCRIPTION
**Pull request by maximelucas**
Addressing #583: initial try for a new gallery that's automatically generated from individual small python scripts.

Right now it's accessible through a new item "Gallery of examples" in the menu. I think it could ultimately be merged with our current Gallery by porting the existing plots into this new format.

Let me know if you like it, and we  can see what to add (now or later).

### CODE REVIEW

**Comment by nwlandry** [comment]
Looks great @maximelucas!! Only comment is that I would remove the "Gallery" tab and examples and remove the "Algorithms" subsection.

**Review by nwlandry — APPROVED** [review]
Looks good! Only comment is wow there are a lot of files --- how does this compare to other libraries?

**Comment by maximelucas** [comment]
Thanks Nich! Most of the files were autogenerated, I removed them. 

Also for the record I only needed to:
- add a few lines to conf.py
- add single .py files for each example

Basically that's it. And to add new examples, we just need to add single `plot_*.py` in the folder `examples/` and its subfolders. 

I put the Gallery visible in the menu too (moved away from dropdown). If you like it I'll merge.

**Comment by nwlandry** [comment]
Looks great! When you merge this PR, can you open an issue to add in some more examples and can you also make sure that the unused pictures and files from the old gallery are deleted?

**Pull request merged**
