### PR TITLE
Create check-urls.yml

### PR DESCRIPTION
**Pull request by nwlandry**
Added a Github Action to check URLs.

### CODE REVIEW

**Comment by maximelucas** [comment]
This amazing, thanks Nich!! 
How do we know it works?
How does it work? For each PR it's gonna tell us if some urls are broken?

**Comment by nwlandry** [comment]
> This amazing, thanks Nich!! How do we know it works? How does it work? For each PR it's gonna tell us if some urls are broken?

That's exactly right. For instance, I already fixed a link because of this failed run: https://github.com/xgi-org/xgi/actions/runs/7077776967

**Comment by maximelucas** [comment]
Great then I'll approve. Does this mean all other urls work fine? Or we'll see at the next PR?

**Review by maximelucas — APPROVED** [review]

**Comment by nwlandry** [comment]
> Great then I'll approve. Does this mean all other urls work fine? Or we'll see at the next PR?

I think that if I'm correct, the link that I fixed was the only issue. And to correct what I said, the action is triggered with every push.

**Pull request merged**
