### PR TITLE
Update publications

### PR DESCRIPTION
**Pull request by nwlandry**

### CODE REVIEW

**Comment by goznalo-git** [comment]
Hey there, I just included a requirements.txt file with xgi within in the repo.
Let me know if you need anything else :)

**Comment by maximelucas** [comment]
This is great, thanks so much @goznalo-git! It will appear on our repo automatically for everyone to see now.

**Comment by nwlandry** [comment]
@maximelucas - thanks for noticing that! @goznalo-git can you make sure that I've cited your papers correctly? I also decided to rename the `Github` button to `Code` like Papers with Code does.

**Comment by goznalo-git** [comment]
Looks good to me!

**Review by maximelucas — APPROVED** [review]

**Pull request merged**
